version: '2'

services:
    # basenode:
    #     build: ./base
    #     stdin_open: true
    #     tty: true
    masternode:
        build: ./master
        stdin_open: true
        tty: true
        expose:
            - 7557
            - 8002
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: rpc
            RPC_PASSWORD: qwerpoiu
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_TARGET_BLOCK_SIZE: target-block-time|30
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
            PARAM_ANYONE_CAN_MINE: anyone-can-mine|true
        volumes:
            - ./master_chain:/root/.multichain            
    slavenode:
        build: ./node
        stdin_open: true
        tty: true
        expose:
            - 7557
            - 8002
        ports:
            - "8002:8002"            
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: rpc
            RPC_PASSWORD: qwerpoiu
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        volumes:
            - ./slave_chain:/root/.multichain
        links:
            - masternode
        depends_on:
            - masternode
    explorernode:
        build: ./explorer
        stdin_open: true
        tty: true
        expose:
            - 2750
            - 7557
            - 8002
        ports: 
            - "2750:2750"
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: rpc
            RPC_PASSWORD: qwerpoiu
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
            volumes:
            - ./explorer_chain:/root/.multichain
        links:
            - masternode
        depends_on:
            - masternode
